# Generated by Django 5.1.2 on 2025-01-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_register_alter_customusers_role'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
        migrations.AlterField(
            model_name='customusers',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='charging_user_set', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='customusers',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='charging_user_set', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
