# Generated by Django 5.1.2 on 2025-01-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_delete_register_alter_customusers_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='contact_number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
