# Generated by Django 5.1.2 on 2025-01-09 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_alter_customusers_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Admin'), (1, 'Adopter'), (2, 'Rehomer')], default=1),
        ),
    ]
