# Generated by Django 5.1.2 on 2025-01-09 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pets', '0004_pet_sterilization'),
        ('Rehomers', '0002_alter_rehomerapplication_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='behaviour',
            field=models.CharField(blank=True, choices=[('Good with adults', 'Good with adults'), ('Good with children', 'Good with children'), ('Good with other dogs', 'Good with other dogs'), ('Needs to be only PET in the home', 'Needs to be only PET in the home'), ('Has lived with other dogs-it was fine', 'Has lived with other dogs-it was fine'), ("Has lived with other dogs-it didn't go well", "Has lived with other dogs-it didn't go well"), ('is fairly relaxed', 'Is fairly relaxed'), ('is active and lively', 'Is active and lively'), ('is only walked on the leash', 'Is only walked on the leash'), ('Can be left alone for short to medium periods', 'Can be left alone for short to medium periods'), ('Has good recall', 'Has good recall'), ('Travel well in cars', 'Travel well in cars'), ('Needs more exercise than most dogs', 'Needs more exercise than most dogs')], default='Good with adults', max_length=100),
        ),
        migrations.AddField(
            model_name='pet',
            name='color',
            field=models.CharField(blank=True, choices=[('Black', 'Black'), ('Brown/Chocolate', 'Brown/Chocolate'), ('Blue', 'Blue'), ('Cream/Fawn/Yellow', 'Cream/Fawn/Yellow'), ('Mixed Color', 'Mixed Color'), ('Red/Ginger', 'Red/Ginger'), ('White', 'White'), ('Silver/Grey', 'Silver/Grey'), ('Gold/Apricot', 'Gold/Apricot'), ('Other', 'Other')], default='Black', max_length=50),
        ),
        migrations.AddField(
            model_name='pet',
            name='household_activity',
            field=models.CharField(blank=True, choices=[('Busy / Noisy', 'Busy / Noisy'), ('Moderate comings and goings', 'Moderate comings and goings'), ('Quiet with occasional guests', 'Quiet with occasional guests')], default='Moderate comings and goings', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='household_environment',
            field=models.CharField(blank=True, choices=[('Busy urban', 'Busy urban'), ('Suburban', 'Suburban'), ('Quiet rural', 'Quiet rural'), ('Farm-like', 'Farm-like')], default='Suburban', max_length=100),
        ),
        migrations.AddField(
            model_name='pet',
            name='lives_with_other_pets',
            field=models.CharField(choices=[('Yes, my pet lives with cats', 'Yes, my pet lives with cats'), ('Yes, my pet lives with dogs', 'Yes, my pet lives with dogs'), ('No, my pet does not live with other pets', 'No, my pet does not live with other pets')], default='No, my pet does not live with other pets', max_length=100),
        ),
        migrations.AddField(
            model_name='pet',
            name='owned_time',
            field=models.CharField(choices=[('less than 1 week', 'Less than 1 week'), ('1 week', '1 week'), ('2 weeks', '2 weeks'), ('3 weeks', '3 weeks'), ('1 month', '1 month'), ('2 months', '2 months'), ('over 2 months', 'Over 2 months')], default='1 week', max_length=50),
        ),
        migrations.AddField(
            model_name='pet',
            name='rehomer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='Rehomers.rehomerprofile'),
        ),
        migrations.AddField(
            model_name='pet',
            name='size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='pet',
            name='socialization_issues',
            field=models.CharField(blank=True, choices=[('Reacts badly to people', 'Reacts badly to people'), ('Rects badly to other dogs', 'Rects badly to other dogs'), ('Is aggresive', 'Is aggressive'), ('Is a barker(to the point of being problematic)', 'Is a barker (to the point of being problematic)'), ('Has separation anxiety', 'Has separation anxiety'), ('Bites or nips', 'Bites or nips'), ('Has no or limited recall', 'Has no or limited recall'), ('Cannot be walked off the leash', 'Cannot be walked off the leash'), ('Pulls on the lead(to the point of being problematic)', 'Pulls on the lead (to the point of being problematic)'), ('Jumps or lunges(to the point of being problematic)', 'Jumps or lunges (to the point of being problematic)'), ('Can demonstrate resource guarding at times', 'Can demonstrate resource guarding at times')], default='Jumps or lunges(to the point of being problematic)', max_length=100),
        ),
        migrations.AddField(
            model_name='pet',
            name='source',
            field=models.CharField(choices=[('Breeder', 'Breeder'), ('Friend/Family', 'Friend/Family'), ('Found', 'Found'), ('Fostered', 'Fostered'), ('Charity/RescueCenter', 'Charity/Rescue Center'), ('PetShop', 'Pet Shop'), ('OwnerSeller/Marketplace', 'Owner Seller/Marketplace'), ('Other', 'Other')], default='Breeder', max_length=50),
        ),
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pet',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pets', to='Pets.petcategory'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10),
        ),
        migrations.AlterField(
            model_name='pet',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_image',
            field=models.ImageField(blank=True, null=True, upload_to='pets/'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='sterilization',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=10),
        ),
    ]
