# Generated by Django 5.1.2 on 2025-01-09 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adopters', '0003_adoptionapplication_adults_and_more'),
        ('Pets', '0005_pet_behaviour_pet_color_pet_household_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='adopter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adopted_pets', to='Adopters.adopterprofile'),
        ),
    ]
