# Generated by Django 5.1.2 on 2025-01-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adopters', '0002_alter_adopterreference_adopter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionapplication',
            name='adults',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='children',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='contact',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='district',
            field=models.CharField(default='Unknown District', max_length=100),
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='garden',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=10),
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='home_type',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='household_activity',
            field=models.CharField(default='Moderate', max_length=255),
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='home_images/'),
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='moving',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=10),
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='other_animals',
            field=models.CharField(blank=True, choices=[('', 'Select'), ('1', '1'), ('2', '2'), ('3', '3'), ('more', 'More than 3')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='vehicle',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=10),
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='visiting_children',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=10),
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='ward',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='work_pattern',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='adoptionapplication',
            name='motivation',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='AdopterReference',
        ),
    ]
